### PR TITLE
adding job template load/unload to Dockerfile command

### PR DESCRIPTION
**Pull request by dharmamike**

### CODE REVIEW

**Comment by dharmamike** [comment]
built upon https://github.com/CenturyLinkLabs/panamax-api/pull/264, so there's a duplicitous commit here

**Comment by alexwelch** [comment]
:+1:

**Comment by alexwelch** [comment]
I say go ahead and merge this so Pat can do his stuff

**Comment by dharmamike** [comment]
I'm with you, @alexwelch

**Pull request merged**
