### PR TITLE
Chore/dray template mods

### PR DESCRIPTION
**Pull request by patocox**
Added sections for new Dray version re: delimiters and links to info about adapters

### CODE REVIEW

**Comment by bdehamer** [comment]
LGTM

**Comment by alexwelch** [comment]
Hang on, getting an error importing:
ActiveRecord::UnknownAttributeError: unknown attribute: beginDelimiter
/var/app/panamax-api/app/builders/job_template_builder.rb:13:in `block in create_steps'
/var/app/panamax-api/app/builders/job_template_builder.rb:12:in `each'
/var/app/panamax-api/app/builders/job_template_builder.rb:12:in `each_with_index'
/var/app/panamax-api/app/builders/job_template_builder.rb:12:in `each'
/var/app/panamax-api/app/builders/job_template_builder.rb:12:in `map'
/var/app/panamax-api/app/builders/job_template_builder.rb:12:in `create_steps'
/var/app/panamax-api/app/builders/job_template_builder.rb:6:in `block in create'
/var/app/panamax-api/app/builders/job_template_builder.rb:5:in `create'
/var/app/panamax-api/app/models/job_template.rb:16:in `block in load_templates'
/var/app/panamax-api/app/models/job_template.rb:14:in `load_templates'
/var/app/panamax-api/lib/tasks/panamax.rake:17:in `block (3 levels) in <top (required)>'
NoMethodError: undefined method `beginDelimiter=' for #<JobTemplateStep:0x007fb779937348>
/var/app/panamax-api/app/builders/job_template_builder.rb:13:in `block in create_steps'
/var/app/panamax-api/app/builders/job_template_builder.rb:12:in `each'
/var/app/panamax-api/app/builders/job_template_builder.rb:12:in `each_with_index'
/var/app/panamax-api/app/builders/job_template_builder.rb:12:in `each'
/var/app/panamax-api/app/builders/job_template_builder.rb:12:in `map'
/var/app/panamax-api/app/builders/job_template_builder.rb:12:in `create_steps'
/var/app/panamax-api/app/builders/job_template_builder.rb:6:in `block in create'
/var/app/panamax-api/app/builders/job_template_builder.rb:5:in `create'
/var/app/panamax-api/app/models/job_template.rb:16:in `block in load_templates'
/var/app/panamax-api/app/models/job_template.rb:14:in `load_templates'
/var/app/panamax-api/lib/tasks/panamax.rake:17:in `block (3 levels) in <top (required)>'
Tasks: TOP => panamax:job_templates:load
(See full trace by running task with --trace)

I'm debugging now

**Comment by rossjimenez** [comment]
+1 LGTM 2

**Comment by alexwelch** [comment]
Closing and merging a different commit with appropriate fixes.

**Pull request closed without merging**
